### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by jmikedupont2** [tlc-pack/libflash_attn#12]
I am having problems getting the exact version of the compilers setup. It would be nice to have some guidance as to what exact build configurations are known to work. maybe some docker or other devops tools would help?

I also found this repo that has more build information, going to look at that
https://github.com/Dao-AILab/flash-attention

**Comment by masahi** [comment]
g++ 11 should work. Yes, https://github.com/Dao-AILab/flash-attention is the original repository from which this repo was created. You probably want to use that one.
