### ISSUE TITLE
Flash-decoding support? 

### ISSUE THREAD

**Issue by tiandiao123** [tlc-pack/libflash_attn#6]
Hi friend:
    did you see flash-attention is currently adding flash-decoding. do you want to add that support in your repo?

**Comment by masahi** [comment]
I intentionally removed flash decoding in https://github.com/tlc-pack/libflash_attn/pull/4 to speed up compile time. I don't need it for now.

**Comment by tiandiao123** [comment]
> I intentionally removed flash decoding in #4 to speed up compile time. I don't need it for now.

Thank you! Let me check!

**Comment by masahi** [comment]
Flash decoding is integrated in https://github.com/tlc-pack/libflash_attn/pull/9
